  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module counter::errors {

  #[error]

  const INVALID_INCREMENT: vector<u8> = b"Number can't be incremented, must be more than 0";

  public fun invalid_increment_error(condition: bool) {
    assert!(condition, INVALID_INCREMENT)
  }
}
