  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module counter::deploy_hook {
  use dubhe::dapp_service::DappHub;

  public(package) fun run(_dapp_hub: &mut DappHub, _ctx: &mut TxContext) {
  }
}
