  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::asset_swap {

  use sui::bcs::{to_bytes};

  use std::ascii::{string, String, into_bytes};

  use dubhe::table_id;

  use dubhe::dapp_service::{Self, DappHub};

  use dubhe::dapp_system;

  use dubhe::dapp_key;

  use dubhe::dapp_key::DappKey;

  const TABLE_NAME: vector<u8> = b"asset_swap";

  const TABLE_TYPE: vector<u8> = b"Resource";

  const OFFCHAIN: bool = true;

  public struct AssetSwap has copy, drop, store {
    from: address,
    asset0: address,
    asset1: address,
    amount0: u256,
    amount1: u256,
    to: address,
  }

  public fun new(
    from: address,
    asset0: address,
    asset1: address,
    amount0: u256,
    amount1: u256,
    to: address,
  ): AssetSwap {
    AssetSwap {
            from,
            asset0,
            asset1,
            amount0,
            amount1,
            to,
        }
  }

  public fun from(self: &AssetSwap): address {
    self.from
  }

  public fun asset0(self: &AssetSwap): address {
    self.asset0
  }

  public fun asset1(self: &AssetSwap): address {
    self.asset1
  }

  public fun amount0(self: &AssetSwap): u256 {
    self.amount0
  }

  public fun amount1(self: &AssetSwap): u256 {
    self.amount1
  }

  public fun to(self: &AssetSwap): address {
    self.to
  }

  public fun update_from(self: &mut AssetSwap, from: address) {
    self.from = from
  }

  public fun update_asset0(self: &mut AssetSwap, asset0: address) {
    self.asset0 = asset0
  }

  public fun update_asset1(self: &mut AssetSwap, asset1: address) {
    self.asset1 = asset1
  }

  public fun update_amount0(self: &mut AssetSwap, amount0: u256) {
    self.amount0 = amount0
  }

  public fun update_amount1(self: &mut AssetSwap, amount1: u256) {
    self.amount1 = amount1
  }

  public fun update_to(self: &mut AssetSwap, to: address) {
    self.to = to
  }

  public fun get_table_id(): String {
    string(TABLE_NAME)
  }

  public fun get_key_schemas(): vector<String> {
    vector[]
  }

  public fun get_value_schemas(): vector<String> {
    vector[string(b"address"), string(b"address"), string(b"address"), string(b"u256"), string(b"u256"),
    string(b"address")
    ]
  }

  public fun get_key_names(): vector<String> {
    vector[]
  }

  public fun get_value_names(): vector<String> {
    vector[string(b"from"), string(b"asset0"), string(b"asset1"), string(b"amount0"), string(b"amount1"),
    string(b"to")
    ]
  }

  public(package) fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    let dapp_key = dapp_key::new();
    dapp_service::register_table(
            dapp_hub,
             dapp_key,
            string(TABLE_TYPE),
            get_table_id(), 
            get_key_schemas(), 
            get_key_names(), 
            get_value_schemas(), 
            get_value_names(), 
            OFFCHAIN,
            ctx
        );
  }

  public(package) fun set(
    dapp_hub: &mut DappHub,
    from: address,
    asset0: address,
    asset1: address,
    amount0: u256,
    amount1: u256,
    to: address,
  ) {
    let key_tuple = vector::empty();
    let value_tuple = encode(from, asset0, asset1, amount0, amount1, to);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple, OFFCHAIN);
  }

  public(package) fun set_struct(dapp_hub: &mut DappHub, asset_swap: AssetSwap) {
    let key_tuple = vector::empty();
    let value_tuple = encode_struct(asset_swap);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple, OFFCHAIN);
  }

  public fun encode(
    from: address,
    asset0: address,
    asset1: address,
    amount0: u256,
    amount1: u256,
    to: address,
  ): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&from));
    value_tuple.push_back(to_bytes(&asset0));
    value_tuple.push_back(to_bytes(&asset1));
    value_tuple.push_back(to_bytes(&amount0));
    value_tuple.push_back(to_bytes(&amount1));
    value_tuple.push_back(to_bytes(&to));
    value_tuple
  }

  public fun encode_struct(asset_swap: AssetSwap): vector<vector<u8>> {
    encode(asset_swap.from, asset_swap.asset0, asset_swap.asset1, asset_swap.amount0, asset_swap.amount1, asset_swap.to)
  }
}
