  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::dapp_fee_state {

  use sui::bcs::{to_bytes};

  use std::ascii::{string, String, into_bytes};

  use dubhe::table_id;

  use dubhe::dapp_service::{Self, DappHub};

  use dubhe::dapp_system;

  use dubhe::dapp_key;

  use dubhe::dapp_key::DappKey;

  const TABLE_NAME: vector<u8> = b"dapp_fee_state";

  const TABLE_TYPE: vector<u8> = b"Resource";

  const OFFCHAIN: bool = false;

  public struct DappFeeState has copy, drop, store {
    base_fee: u256,
    byte_fee: u256,
    free_credit: u256,
    total_bytes_size: u256,
    total_recharged: u256,
    total_paid: u256,
    total_set_count: u256,
  }

  public fun new(
    base_fee: u256,
    byte_fee: u256,
    free_credit: u256,
    total_bytes_size: u256,
    total_recharged: u256,
    total_paid: u256,
    total_set_count: u256,
  ): DappFeeState {
    DappFeeState {
            base_fee,
            byte_fee,
            free_credit,
            total_bytes_size,
            total_recharged,
            total_paid,
            total_set_count,
        }
  }

  public fun base_fee(self: &DappFeeState): u256 {
    self.base_fee
  }

  public fun byte_fee(self: &DappFeeState): u256 {
    self.byte_fee
  }

  public fun free_credit(self: &DappFeeState): u256 {
    self.free_credit
  }

  public fun total_bytes_size(self: &DappFeeState): u256 {
    self.total_bytes_size
  }

  public fun total_recharged(self: &DappFeeState): u256 {
    self.total_recharged
  }

  public fun total_paid(self: &DappFeeState): u256 {
    self.total_paid
  }

  public fun total_set_count(self: &DappFeeState): u256 {
    self.total_set_count
  }

  public fun update_base_fee(self: &mut DappFeeState, base_fee: u256) {
    self.base_fee = base_fee
  }

  public fun update_byte_fee(self: &mut DappFeeState, byte_fee: u256) {
    self.byte_fee = byte_fee
  }

  public fun update_free_credit(self: &mut DappFeeState, free_credit: u256) {
    self.free_credit = free_credit
  }

  public fun update_total_bytes_size(self: &mut DappFeeState, total_bytes_size: u256) {
    self.total_bytes_size = total_bytes_size
  }

  public fun update_total_recharged(self: &mut DappFeeState, total_recharged: u256) {
    self.total_recharged = total_recharged
  }

  public fun update_total_paid(self: &mut DappFeeState, total_paid: u256) {
    self.total_paid = total_paid
  }

  public fun update_total_set_count(self: &mut DappFeeState, total_set_count: u256) {
    self.total_set_count = total_set_count
  }

  public fun get_table_id(): String {
    string(TABLE_NAME)
  }

  public fun get_key_schemas(): vector<String> {
    vector[
    string(b"String")
    ]
  }

  public fun get_value_schemas(): vector<String> {
    vector[string(b"u256"), string(b"u256"), string(b"u256"), string(b"u256"), string(b"u256"), string(b"u256"),
    string(b"u256")
    ]
  }

  public fun get_key_names(): vector<String> {
    vector[
    string(b"dapp_key")
    ]
  }

  public fun get_value_names(): vector<String> {
    vector[string(b"base_fee"), string(b"byte_fee"), string(b"free_credit"), string(b"total_bytes_size"), string(b"total_recharged"), string(b"total_paid"),
    string(b"total_set_count")
    ]
  }

  public(package) fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    let dapp_key = dapp_key::new();
    dapp_service::register_table(
            dapp_hub,
             dapp_key,
            string(TABLE_TYPE),
            get_table_id(), 
            get_key_schemas(), 
            get_key_names(), 
            get_value_schemas(), 
            get_value_names(), 
            OFFCHAIN,
            ctx
        );
  }

  public fun has(dapp_hub: &DappHub, dapp_key: String): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    dapp_service::has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_has(dapp_hub: &DappHub, dapp_key: String) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    dapp_service::ensure_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_not_has(dapp_hub: &DappHub, dapp_key: String) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    dapp_service::ensure_not_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public(package) fun delete(dapp_hub: &mut DappHub, dapp_key: String) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    dapp_service::delete_record<DappKey>(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, OFFCHAIN);
  }

  public fun get_base_fee(dapp_hub: &DappHub, dapp_key: String): u256 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0);
    let mut bsc_type = sui::bcs::new(value);
    let base_fee = sui::bcs::peel_u256(&mut bsc_type);
    base_fee
  }

  public(package) fun set_base_fee(dapp_hub: &mut DappHub, dapp_key: String, base_fee: u256) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value = to_bytes(&base_fee);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 0, value, OFFCHAIN);
  }

  public fun get_byte_fee(dapp_hub: &DappHub, dapp_key: String): u256 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1);
    let mut bsc_type = sui::bcs::new(value);
    let byte_fee = sui::bcs::peel_u256(&mut bsc_type);
    byte_fee
  }

  public(package) fun set_byte_fee(dapp_hub: &mut DappHub, dapp_key: String, byte_fee: u256) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value = to_bytes(&byte_fee);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 1, value, OFFCHAIN);
  }

  public fun get_free_credit(dapp_hub: &DappHub, dapp_key: String): u256 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 2);
    let mut bsc_type = sui::bcs::new(value);
    let free_credit = sui::bcs::peel_u256(&mut bsc_type);
    free_credit
  }

  public(package) fun set_free_credit(dapp_hub: &mut DappHub, dapp_key: String, free_credit: u256) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value = to_bytes(&free_credit);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 2, value, OFFCHAIN);
  }

  public fun get_total_bytes_size(dapp_hub: &DappHub, dapp_key: String): u256 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 3);
    let mut bsc_type = sui::bcs::new(value);
    let total_bytes_size = sui::bcs::peel_u256(&mut bsc_type);
    total_bytes_size
  }

  public(package) fun set_total_bytes_size(dapp_hub: &mut DappHub, dapp_key: String, total_bytes_size: u256) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value = to_bytes(&total_bytes_size);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 3, value, OFFCHAIN);
  }

  public fun get_total_recharged(dapp_hub: &DappHub, dapp_key: String): u256 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 4);
    let mut bsc_type = sui::bcs::new(value);
    let total_recharged = sui::bcs::peel_u256(&mut bsc_type);
    total_recharged
  }

  public(package) fun set_total_recharged(dapp_hub: &mut DappHub, dapp_key: String, total_recharged: u256) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value = to_bytes(&total_recharged);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 4, value, OFFCHAIN);
  }

  public fun get_total_paid(dapp_hub: &DappHub, dapp_key: String): u256 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 5);
    let mut bsc_type = sui::bcs::new(value);
    let total_paid = sui::bcs::peel_u256(&mut bsc_type);
    total_paid
  }

  public(package) fun set_total_paid(dapp_hub: &mut DappHub, dapp_key: String, total_paid: u256) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value = to_bytes(&total_paid);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 5, value, OFFCHAIN);
  }

  public fun get_total_set_count(dapp_hub: &DappHub, dapp_key: String): u256 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 6);
    let mut bsc_type = sui::bcs::new(value);
    let total_set_count = sui::bcs::peel_u256(&mut bsc_type);
    total_set_count
  }

  public(package) fun set_total_set_count(dapp_hub: &mut DappHub, dapp_key: String, total_set_count: u256) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value = to_bytes(&total_set_count);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 6, value, OFFCHAIN);
  }

  public fun get(dapp_hub: &DappHub, dapp_key: String): (u256, u256, u256, u256, u256, u256, u256) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value_tuple = dapp_service::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    let mut bsc_type = sui::bcs::new(value_tuple);
    let base_fee = sui::bcs::peel_u256(&mut bsc_type);
    let byte_fee = sui::bcs::peel_u256(&mut bsc_type);
    let free_credit = sui::bcs::peel_u256(&mut bsc_type);
    let total_bytes_size = sui::bcs::peel_u256(&mut bsc_type);
    let total_recharged = sui::bcs::peel_u256(&mut bsc_type);
    let total_paid = sui::bcs::peel_u256(&mut bsc_type);
    let total_set_count = sui::bcs::peel_u256(&mut bsc_type);
    (base_fee, byte_fee, free_credit, total_bytes_size, total_recharged, total_paid, total_set_count)
  }

  public(package) fun set(
    dapp_hub: &mut DappHub,
    dapp_key: String,
    base_fee: u256,
    byte_fee: u256,
    free_credit: u256,
    total_bytes_size: u256,
    total_recharged: u256,
    total_paid: u256,
    total_set_count: u256,
  ) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value_tuple = encode(base_fee, byte_fee, free_credit, total_bytes_size, total_recharged, total_paid, total_set_count);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple, OFFCHAIN);
  }

  public fun get_struct(dapp_hub: &DappHub, dapp_key: String): DappFeeState {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value_tuple = dapp_service::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    decode(value_tuple)
  }

  public(package) fun set_struct(dapp_hub: &mut DappHub, dapp_key: String, dapp_fee_state: DappFeeState) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&dapp_key));
    let value_tuple = encode_struct(dapp_fee_state);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple, OFFCHAIN);
  }

  public fun encode(
    base_fee: u256,
    byte_fee: u256,
    free_credit: u256,
    total_bytes_size: u256,
    total_recharged: u256,
    total_paid: u256,
    total_set_count: u256,
  ): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&base_fee));
    value_tuple.push_back(to_bytes(&byte_fee));
    value_tuple.push_back(to_bytes(&free_credit));
    value_tuple.push_back(to_bytes(&total_bytes_size));
    value_tuple.push_back(to_bytes(&total_recharged));
    value_tuple.push_back(to_bytes(&total_paid));
    value_tuple.push_back(to_bytes(&total_set_count));
    value_tuple
  }

  public fun encode_struct(dapp_fee_state: DappFeeState): vector<vector<u8>> {
    encode(dapp_fee_state.base_fee, dapp_fee_state.byte_fee, dapp_fee_state.free_credit, dapp_fee_state.total_bytes_size, dapp_fee_state.total_recharged, dapp_fee_state.total_paid, dapp_fee_state.total_set_count)
  }

  public fun decode(data: vector<u8>): DappFeeState {
    let mut bsc_type = sui::bcs::new(data);
    let base_fee = sui::bcs::peel_u256(&mut bsc_type);
    let byte_fee = sui::bcs::peel_u256(&mut bsc_type);
    let free_credit = sui::bcs::peel_u256(&mut bsc_type);
    let total_bytes_size = sui::bcs::peel_u256(&mut bsc_type);
    let total_recharged = sui::bcs::peel_u256(&mut bsc_type);
    let total_paid = sui::bcs::peel_u256(&mut bsc_type);
    let total_set_count = sui::bcs::peel_u256(&mut bsc_type);
    DappFeeState {
            base_fee,
            byte_fee,
            free_credit,
            total_bytes_size,
            total_recharged,
            total_paid,
            total_set_count,
        }
  }
}
