  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::account_status {

  use sui::bcs::{BCS, to_bytes, peel_enum_tag};

  public enum AccountStatus has copy, drop, store {
        Blocked,Frozen,Liquid
    }

  public fun new_blocked(): AccountStatus {
    AccountStatus::Blocked
  }

  public fun new_frozen(): AccountStatus {
    AccountStatus::Frozen
  }

  public fun new_liquid(): AccountStatus {
    AccountStatus::Liquid
  }

  public fun encode(self: AccountStatus): vector<u8> {
    to_bytes(&self)
  }

  public fun decode(bytes: &mut BCS): AccountStatus {
    match(peel_enum_tag(bytes)) {
            0 => AccountStatus::Blocked,
            1 => AccountStatus::Frozen,
            2 => AccountStatus::Liquid,
            _ => abort,
        }
  }
}
