  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::asset_status {

  use sui::bcs::{BCS, to_bytes, peel_enum_tag};

  public enum AssetStatus has copy, drop, store {
        Frozen,Liquid
    }

  public fun new_frozen(): AssetStatus {
    AssetStatus::Frozen
  }

  public fun new_liquid(): AssetStatus {
    AssetStatus::Liquid
  }

  public fun encode(self: AssetStatus): vector<u8> {
    to_bytes(&self)
  }

  public fun decode(bytes: &mut BCS): AssetStatus {
    match(peel_enum_tag(bytes)) {
            0 => AssetStatus::Frozen,
            1 => AssetStatus::Liquid,
            _ => abort,
        }
  }
}
